# Generated by Django 5.1.2 on 2024-11-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Projectinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('viewcount', models.IntegerField()),
                ('day', models.CharField(max_length=30)),
                ('file_url', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.menu')),
            ],
            options={
                'db_table': 'projectinfo',
            },
        ),
        migrations.CreateModel(
            name='Projectimg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_title', models.CharField(max_length=100)),
                ('img1', models.CharField(max_length=100, null=True)),
                ('img2', models.CharField(max_length=100, null=True)),
                ('img3', models.CharField(max_length=100, null=True)),
                ('img4', models.CharField(max_length=100, null=True)),
                ('img5', models.CharField(max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectinfo')),
            ],
            options={
                'db_table': 'projectimg',
            },
        ),
    ]
