# Generated by Django 5.1.2 on 2024-11-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Projectinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('viewcount', models.IntegerField()),
                ('day', models.CharField(max_length=30)),
                ('file_url', models.CharField(max_length=100)),
                ('img_title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.menu')),
            ],
            options={
                'db_table': 'projectinfo',
            },
        ),
        migrations.CreateModel(
            name='Searchtitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.menu')),
            ],
            options={
                'db_table': 'searchtitle',
            },
        ),
        migrations.CreateModel(
            name='Slideimg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slide_img', models.CharField(max_length=100)),
                ('projectinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectinfo')),
            ],
            options={
                'db_table': 'slideimg',
            },
        ),
    ]
